### ISSUE TITLE
I can't log in from Tokyo

### ISSUE THREAD

**Issue by daisukenagata** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#1]
Hello, we confirmed a sample of the SDK. I'm told I'm logged in during signup, but I can't log in. Is there a solution?

<p align="center">
<img src=https://user-images.githubusercontent.com/16457165/70622673-c91fd980-1c5f-11ea-888a-2435da4bda9f.jpeg width="350" height="700">
</p>

**Comment by daisukenagata** [comment]
Since the parameter is not passed to validationData on the sign screen, it becomes 100% nil, and the data cannot be acquired.

```ruby
/// Signs in a user with the given username and password.

/// - Parameters:
///   - username: username of the user.
///   - password: password of the user.
///   - validationData: validation data for this sign in.
///   - completionHandler: completionHandler which will be called when result is available.
public func signIn(username: String, password: String, validationData: [String: String]? = nil, completionHandler: @escaping ((SignInResult?, Error?) -> Void))
```

**Comment by dswamina** [comment]
We did confirm that the SignIn/SignUp are working successfully with the tokyo region credentials for AWS Tokyo region.

Please check if you have updated the  Constants.swift as follows :


Open Constants.swift. Set CognitoIdentityUserPoolRegion, CognitoIdentityUserPoolId, CognitoIdentityUserPoolAppClientId and CognitoIdentityUserPoolAppClientSecret to the values obtained when you created your user pool.
```
        let CognitoIdentityUserPoolRegion = AWSRegionType.APNortheast1
```

This `CognitoIdentityUserPoolRegion` in `Constants.swift` is currently hardcoded to AWSRegionType.USWest2, can you switch it to the region where you created the userpool?

If the above steps did not resolve your sign-in issue:

-  let us know the exact steps to reproduce the error.
- Additionally, please also let know the signInResult : In the `SignInViewController.swift`, print the `signInResult.signInState` at `line 61` and let us know the output to get a better understanding of the sign in error.

**Comment by daisukenagata** [comment]
The registration from the management screen did not work in FORCE_CHANGE_PASSWORD state.

<p align="center">
<img src=https://user-images.githubusercontent.com/16457165/70667412-280f3e00-1cb4-11ea-8100-94372960c020.PNG width="350" height="700">
</p>

I solved it by signing up from my mobile phone and setting the password to CONFIRMED. Thank you very much.
