### ISSUE TITLE
WebRTC Crash dSYM

### ISSUE THREAD

**Issue by AshrafJaddo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#11]
We did follow the documented steps to get WebRTC and include it in our Kinesis based App, similar to the Sample App.

We did not see any issues during development but as usual in production our crash tool (BugSnag) started to report events from WebRTC, they are not symbolized because we do not have the dSYM file. 

Any steps to get the dSYM file so I can upload it to BugSnag to see the stack from WebRTC crashes?

**Comment by hassanctech** [comment]
@AshrafJaddo were you able to figure this out?

**Comment by AshrafJaddo** [comment]
unfortunately no. we ended up having a wrapper in our code for each WebRTC method we used so we can see our in stack what API failed in WebRTC.

**Comment by MushMal** [comment]
Resolving this for now
