### ISSUE TITLE
Get Video Url from live streaming

### ISSUE THREAD

**Issue by dhruv-dhola** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#12]
hello 
I am working on Aws Webrtc live streaming on ios And Any idea how we get URL Video  from live Streaming

**Comment by lherman-cs** [comment]
@dhruv-dhola do you mind to share your use case? In WebRTC, there's generally no such thing as URL since the data is transferred in peer-to-peer or through a relay.

**Comment by MushMal** [comment]
Any update?

**Comment by sharadrj** [comment]
Closing now.
