### ISSUE TITLE
Getting payload error where more than one viewer view the live stream

### ISSUE THREAD

**Issue by gkumarlnct** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#15]
Hi, We are using Kinesis Video stream for the live video streaming also have done setup for the ios application as well as backend, But while running the same we cant able to see if number of viewer increase from one. Also we have tried to run viewer one from the application and other from the AWS console and also from the multiple ios devices but still we are getting the error.

We are getting this error.
"Additional signaling messages "
Event =
payload Error Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}

Please provide a solution for the same as we require some simple and perfect solution for the live video streaming for our IOS application.

 Thanks & Regard
Gaurav Kumar

**Comment by dswamina** [comment]
Hi,

Thank you for contacting us and bringing the error to our notice. 
Can you please elaborate a little bit more on the setup? 
Which SDK are you using to start the primary connection? 
How many viewers are connected to the Primary? 

Thanks, 
Divya

**Comment by MushMal** [comment]
Resolving as stale

**Comment by farmeng** [comment]
We encountered the same issue. Any ideas on how to fix it?
