### ISSUE TITLE
How to record remote audio to a file?

### ISSUE THREAD

**Issue by bijuC1983** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#17]
Hello, 
          The use case is to record the remote video & audio to a single file. I am able to successfully record the video by

- By overriding the renderFrame method in RTCVideoRenderer, I get access to every RTCVideoFrame. 

- If recording has started, every RTCVideoFrame is converted to CMSampleBuffer and appended to the VideoInput of the AVAssetWriter

This works perfectly fine. I have checked throughout but cannot find a way to hook the remote audio to the AudioInput of the AVAssetWriter. There is no delegate present in the RTCAudioSource or RTCAudioTrack. 
Please guide what is the right way to do it as it is a very common use case and other applications with WebRTC are doing it.

Thanks in advance!

**Comment by hassanctech** [comment]
Unfortunately we're not able to provide any assistance there.  We suggest going to the iOS dev forums for this type of question.

**Comment by sanjaykmwt94222** [comment]
Did you find a solution to that?

**Comment by bijuC1983** [comment]
@sanjaykmwt94222 Unfortunately I have not found a solution yet. There are a few threads on Stackoverflow and other forums on this, but none with the proper solution for Remote Audio recording.
I have added https://stackoverflow.com/questions/64987571/how-to-record-remote-audio-during-webrtc-using-aws-kinesis-webrtc-ios-sdk myself too but no responses.
Are you also facing the same?

**Comment by codemeister64** [comment]
Hi, could you please share your solution of how you convert RTCVideoFrame to CMSampleBuffer and obtain valid CMFormatDescription? I’m also faced with this issue, but I’m right at the beginning.

**Comment by bijuC1983** [comment]
Hi @codemeister64  Sorry for the delay in response and hope this helps.
This is the code I use
` if let rtcPixelBuffer = incomingFrame.buffer as? RTCCVPixelBuffer{
                       let sample = self.getCMSampleBuffer(pixelBuffer: rtcPixelBuffer.pixelBuffer, timestamp:  incomingFrame?.timeStampNs ?? 0)
}

func getCMSampleBuffer(pixelBuffer: CVPixelBuffer, timestamp: Int64) -> CMSampleBuffer {
        var timingInfo = CMSampleTimingInfo()
        let scale = CMTimeScale(NSEC_PER_SEC)
        let pts = CMTime(value: CMTimeValue(Double(timestamp)),
                         timescale: scale)
        timingInfo = CMSampleTimingInfo(duration: CMTime.invalid,
                                        presentationTimeStamp: pts,
                                        decodeTimeStamp: CMTime.invalid)
        
        var formatDesc: CMFormatDescription? = nil
        CMVideoFormatDescriptionCreateForImageBuffer(allocator: kCFAllocatorDefault, imageBuffer: pixelBuffer, formatDescriptionOut: &formatDesc)
        
        var sampleBuffer: CMSampleBuffer? = nil
        
        CMSampleBufferCreateReadyWithImageBuffer(allocator: kCFAllocatorDefault,
                                                 imageBuffer: pixelBuffer,
                                                 formatDescription: formatDesc!,
                                                 sampleTiming: &timingInfo,
                                                 sampleBufferOut: &sampleBuffer);
        
        return sampleBuffer!
    }
`

**Comment by maxwell44** [comment]
hi，friend
It is now September 2022，Did you find a solution to that?

**Comment by CoderZYLiao** [comment]
hi，friend
It is now September 2024，Did you find a solution to that?
