### ISSUE TITLE
Persisting or storing the stream in kinesis video stream

### ISSUE THREAD

**Issue by SanthoshMKunthe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#20]
Hi I understand we can send video peer-to-peer from : 

- IOS device to iOS device
- iOS device to embedded SDK
- IOS device to web browser

However is there a method to send the video to "kinesis video stream" as we do in producer SDK of Android or C or C++ producer SDK for storing purpose. . .

 I **do not** want to send from one device to another device. . . I want to send from iOS device to store in Kinesis video stream. . .

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues/36#issuecomment-703790063 mentions _"one of the ways I suggest is to run dual streaming mode where there is a parallel stream being uploaded to KVS."_ but there is no documentation on how to perform the same. . . I do not want parallel stream, I want only one stream to be uploaded to KVS. . . Kindly shed some light and provide a required documentation. . .

**Comment by MushMal** [comment]
@SanthoshMKunthe WebRtc as a technology is primarily designed for peering scenarios. We don't support persistence or uploading into KVS using WebRtc. You could, however, have a peer in the cloud that your device communicates to and that, in turn could produce into KVS.

**Comment by SanthoshMKunthe** [comment]
@MushMal  thanks for reaching and helping out. . . Is there any way that I can store video live from iOS device in KVS. . .

**Comment by MushMal** [comment]
While we don’t have an iOS specific build, one could try to compile the producer sdk for iOS. Unfortunately, I don’t have any info on this

**Comment by disa6302** [comment]
Closing this issue based on comment.
