### ISSUE TITLE
How to send customize message?

### ISSUE THREAD

**Issue by MrShiY** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#25]
I want to let master send message to viewers, how to do it?  What is the 'action' of customize message?  I cannot find any document about it.

**Comment by pankeshpatel** [comment]
@MrShiY : As per documentation, "master" and "viewer" are defined as follows: 



Master
A peer that initiates the connection and is connected to the signaling channel with the ability to discover and exchange media with any of the signaling channel's connected viewers.

Viewer
A peer that is connected to the signaling channel with the ability to discover and exchange media only with the signaling channel's master.

**Comment by MushMal** [comment]
@MrShiY all the information is in the API reference guide https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis.html

Please cut a new issue if you have further questions regarding the APIs

**Comment by MrShiY** [comment]
Hi @MushMal ，I have implemented all the features in demo, it works well. Now I want to add a new feature which is let user type message and send using the existing websocket. Your demo doesn’t have this, websocket api document you mentioned doesn’t clear the associated description.

**Comment by MushMal** [comment]
The existing signaling service does not allow for custom messages.

Take a look at data channels - perhaps this is what you need.

**Comment by MrShiY** [comment]
Thanks @MushMal , could you please provide me the document link?

**Comment by MushMal** [comment]
iOS seems to have a few examples of DataChannels

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/eca0d651f09b3716cfb37aa787435e14e1c2f1ae/Swift/KVSiOSApp/WebRTCClient.swift#L218

You can look at https://webrtc.org/getting-started/data-channels
