### ISSUE TITLE
AWSMobileClient 2.21.1 - Could not find module 'AWSMobileClient' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

### ISSUE THREAD

**Issue by HiLittlePiper** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#27]
Hi,

After updated the AWSMobileClient 2.21.1,  I found the "Could not find module 'AWSMobileClient' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios" error message appeared, my Xcode Version is 12.3. Please kindly advise how to fix this.

thanks

**Comment by hassanctech** [comment]
It appears that Apple has removed support for the 32-bit platforms starting from iOS 11 (including 'armv7-apple-ios'), hence it makes sense it's been removed from our latest versions as well.  You will need to use an older version of AWSMobileClient if you require support for this, or perhaps engage on this GitHub page to get more details:  https://github.com/aws-amplify/aws-sdk-ios/issues

**Comment by HiLittlePiper** [comment]
It seems that app has to change the iOS version to iOS11 or later if want to use the latest version of AWSMobileClient, is it right?

**Comment by hassanctech** [comment]
Yes, the new min required iOS version is 11.
