### ISSUE TITLE
How to support the H264 which the profile-level-id is 42e01f

### ISSUE THREAD

**Issue by HiLittlePiper** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#29]
Hi,

because the target embedded camera only support H264 which the profile-level-id is 42e01f, iOS app also want to support this kind of H264, but from the iOS WebRTC SDK, it only support H264 which profile-level-id are 640c2a and 42e02a. it will lead the video cannot be decoded successfully.  I also try to customize the profile-level-id with 42e01f and forbid other profile-level-id, however, the video cannot be rendered any more. Could you please point out how to support this kind of H264 format? appreciate for help.

thanks

**Comment by HiLittlePiper** [comment]
Could someone please provide some suggestion for this?

**Comment by disa6302** [comment]
@HiLittlePiper , 

Can you mention how you customized the profile level on iOS?

**Comment by HiLittlePiper** [comment]
I created a new class to inherit RTCDefaultVideoEncoderFactory class, and rewrote the supportedCodecs() function, then created the RTCPeerConnectionFactory with them. maybe I missed something for this, please kindly advise this. thanks.

-------------------------------------------------
**1).  customized the profile**
class RTCCustomVideoEncoderFactory: RTCDefaultVideoEncoderFactory {
    override func supportedCodecs() -> [RTCVideoCodecInfo] {
        var infos = super.supportedCodecs()
        
        let constrainedHighParams: [String : String] = [
            "profile-level-id": "42e01f",
            "level-asymmetry-allowed": "1",
            "packetization-mode": "1"
        ]
        
        let rvc = RTCVideoCodecInfo(name: "H264", parameters: constrainedHighParams)
        
        infos.append(rvc)
        
        return [rvc]
        
    }
}

class RTCCustomVideoDecoderFactory: RTCDefaultVideoDecoderFactory {
    override func supportedCodecs() -> [RTCVideoCodecInfo] {
        var infos = super.supportedCodecs()
        
        let constrainedHighParams: [String : String] = [
            "profile-level-id": "42e01f",
            "level-asymmetry-allowed": "1",
            "packetization-mode": "1"
        ]
        
        let rvc = RTCVideoCodecInfo(name: "H264", parameters: constrainedHighParams)
        
        infos.append(rvc)
        
        return [rvc]
        
    }
}

**2)  create RTCPeerConnectionFactory**
RTCPeerConnectionFactory(encoderFactory: RTCCustomVideoEncoderFactory(),
                                        decoderFactory: RTCCustomVideoDecoderFactory())

**Comment by disa6302** [comment]
@HiLittlePiper , 

I am not familiar with the WebRTC implementation for iOS. So I am unable to give a suggestion about your piece of right away. However, to see if the profile with 42e01f is being generated, I would suggest you to look at the offer and the answer to see how the media lines look. Confirm if the SDP from the iOS device contains the `42e01f` profile. 

Also, to confirm, is the other peer running the C SDK?

**Comment by HiLittlePiper** [comment]
After customized the  42e01f profile, from the log I caught, I found this kind of profile is contained in the offer and answer. 

Yes, the Master is embedded camera running the C SDK, and iOS app as Viewer will connect it.

**Comment by disa6302** [comment]
@HiLittlePiper ,

If I understand correctly, it looks like the C SDK is unable to decode the stream. I would like to check the C SDK logs to see if it catches anything. Can you attach the logs and also attach the SDP? On the C SDK end, you can run `export DEBUG_LOG_SDP=TRUE` to capture the SDPs in the logs.

**Comment by disa6302** [comment]
@HiLittlePiper ,

If this issue is opened by your team in https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1033, I would suggest to close this out to continue discussions in the C SDK issue.

**Comment by MushMal** [comment]
Closing this in favor of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1033
