### ISSUE TITLE
Starscream Error: Invalid HTTP upgrade

### ISSUE THREAD

**Issue by vico-aguado** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#31]
Hi!

I downloaded this demo, but when I run in simulator and device, I get this message in console:

Starscream 3.0:
WSError(type: Starscream.ErrorType.upgradeError, message: \"Invalid HTTP upgrade\", code: 403) 

Starscream >=4.0:
Starscream.HTTPUpgradeError.notAnUpgrade(403)

What's wrong? 

Help me, please!! 

Thanks for all!

**Comment by disa6302** [comment]
@vico-aguado , 

Do you know if the `pod install` ran with no errors?
Did you make any changes on the demo?

**Comment by bartoslaw** [comment]
@vico-aguado in my case it turned out iso8601 date used in KVSSigner function was wrong.

this is the method i changed it to

```
static func iso8601() -> (fullDateTimestamp: String, shortDate: String) {
        let dateFormatter: ISO8601DateFormatter = ISO8601DateFormatter()
        
        let date = Date()
        let dateString = dateFormatter.string(from: date).replacingOccurrences(of: ":", with: "").replacingOccurrences(of: "-", with: "")
        let index = dateString.index(dateString.startIndex, offsetBy: 8)
        let shortDate = dateString.substring(to: index)
        return (fullDateTimestamp: dateString, shortDate: shortDate)
    }
```
please note i'm using AWSStaticCredentials instead of Cognito, also please make sure to update StarScream library (i'm on 4.0.4), it throws more meaningful errors

**Comment by disa6302** [comment]
@vico-aguado , 

Closing since issue has gone stale. Feel free to re-open if you still face issues.
