### ISSUE TITLE
Sign up (ContinueWith Block) not being executed

### ISSUE THREAD

**Issue by archidvignesh** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#34]
I have built and ran the project on a real device successfully. I also followed the steps on creating an amazon cognito identity and user pools and pasted the values. What happens is, when I provide a username, password and userAttributes to the sign up method on self.pool, the "continueWith" block just doesn't execute. No crashes and no further execution. Any directions from here on?

**Comment by archidvignesh** [comment]
@disa6302 
Thanks for your response: 

I am currently running this on iOS 14.3
Real Device - iPhone 11

I followed the steps outlined in the Kinesis video streams iOS SDK page, created user pools and identity pools and installed the libraries. 

The code is able to detect that no user is present and so it shows the login page. So far so good. When I go to the sign up page, provide new user credentials and hit the sign up button, it doesn't seem to work. No crashes nothing.

On attaching breakpoints,
The sign up code is called but nothing inside the continue with block gets executed. I am not sure how to provide logs as I've never done that before (intermediate skilled programmer) but here is the part that does not execute:

<img width="966" alt="Screenshot 2021-03-10 at 10 36 51" src="https://user-images.githubusercontent.com/56962646/110579320-93341280-818c-11eb-96a8-cd027b3f94ac.png">

Signup method called but nothing inside the block is executed. No errors as well.

**Comment by disa6302** [comment]
@archidvignesh , 

When you click the run button, you should be able to see logs in the Output section. 
The logs might reveal something. Without getting a stack trace/logs, it might be difficult to understand why it blocks on the Sign up method.

**Comment by archidvignesh** [comment]
@disa6302 Ok I will post the logs before the weekend is over and add screenshots. Will update you

**Comment by disa6302** [comment]
Closing due to no response. Fee free to reopen once you have some logs and stack trace.

**Comment by archidvignesh** [comment]
@disa6302 Yes sorry about that just been caught up with some other stuff. Definitely an issue exists and I will re-open once i have proper logs and screenshots
