### ISSUE TITLE
How many viewers can simultaneously connect on a single channel at a time?

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#35]
How many viewers can simultaneously connect on a single channel at a time?

**Comment by hassanctech** [comment]
If you're asking how many viewers a signaling channel supports the answer is 10, see here for more details:  https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-how-it-works.html.
