### ISSUE TITLE
High latency observed while establishing WebRTC connection

### ISSUE THREAD

**Issue by bijuC1983** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#36]
On an average, it is observed that the connection takes ~4 seconds to get established and majority of that time is used in ICE Candidate negotiation.
![Screenshot 2021-03-16 at 4 31 19 PM](https://user-images.githubusercontent.com/8036186/111609539-6ae98b00-8800-11eb-8c4d-07c68e5a248f.png)

- Region: ap-south-1
- Channel name: G00201PS000002

I took a sample of 20 for both Wifi and 4G connection. The results are compiled here:
[WebRTCTestRuns.xlsx](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/files/6163179/WebRTCTestRuns.xlsx)

We have 5 internal testers using the app on a daily basis switching between wifi and 4G; also at various times of the day. The general consensus is that it takes between 4 to 5 seconds to connect in iOS and 2 to 3 seconds to connect in Android which prompted me to get the time elapsed at each step for iOS. We will be also be putting in logs to capture the elapsed time for each step in Android in couple of days for comparison.

**Comment by disa6302** [comment]
@bijuC1983 ,

From your logs, it looks like answer takes 2.9 seconds in itself.

**Comment by disa6302** [comment]
@bijuC1983 ,

I am closing this issue since it has gone stale. Feel free to re-open if you have more information.
