### ISSUE TITLE
Git issue -  pathspec 'Swift/Pods/AWSCore/AWSCore/Service/AWSService.m' did not match any file(s) known to git

### ISSUE THREAD

**Issue by archidvignesh** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#37]
This could be a documentation issue or maybe I am doing something wrong on my part. I have followed the steps outlined in this documentation exactly:
[`https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-ios.html`](url)

**Here is where I am stuck**

<img width="751" alt="Screenshot 2021-04-03 at 20 18 12" src="https://user-images.githubusercontent.com/56962646/113482247-5ae9d080-94bb-11eb-82c0-4dc3bad34ae9.png">

**This is the message i am getting on terminal**

<img width="990" alt="Screenshot 2021-04-03 at 20 18 41" src="https://user-images.githubusercontent.com/56962646/113482257-676e2900-94bb-11eb-897e-86470a89f913.png">

Is the documentation outdated or am I doing something wrong? I cloned the project, cleared pods cache rebuilt it and did everything as instructed but this one step fails. New to version control so any help would be appreciated. Thank you!

**Comment by disa6302** [comment]
Please follow the documentation on github.
