### ISSUE TITLE
WebRTC Framework with bitcode enabled size

### ISSUE THREAD

**Issue by bartoslaw** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#38]
Hello,

We have a following issue:

we were going through your WebRTC + iOS SDK documentation and included all the pods from the [sample](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-ios.html) in our project, but `GoogleWebRTC` dependency provides framework without bitcode enabled.

After following those instructions https://webrtc.github.io/webrtc-org/native-code/ios/ we were able to create a WebRTC.framework with bitcode enabled, the issue is, that even after stripping not needed architectures this framework is ~650mb

This create a problem because our application size after including this framework is almost 800mb, that's way too much.

Is there another way to configure webrtc + kvs that's not described in the documentation to avoid this?

Additional info:
- our application is built as a modular application - [reference](https://medium.com/flawless-app-stories/a-modular-architecture-in-swift-aafd9026aa99) 
- we're using `AWSBasicAuthorizationCredentials` instead of `AWSCognito` (not sure if that matters in this case)

**Comment by disa6302** [comment]
Our iOS SDK has a very small memory footprint because it is mostly using the WebRTC native iOS SDK. So this question is better directed to the WebRTC forums.
