### ISSUE TITLE
Sign In Crashes

### ISSUE THREAD

**Issue by bekzodrakhmatof** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#39]
Hi AWSLABS Team,

I have been implementing WebRTC app using this sdk but when I test sample I get crash if I try to Sign In.

In screenshot below user is nil. 

Let me know if I am doing something wrong! Thank you!

<img width="869" alt="Screen Shot 2021-04-13 at 7 04 35 PM" src="https://user-images.githubusercontent.com/23249828/114535500-17e1e700-9c8b-11eb-896f-22568bb25911.png">

**Comment by archidvignesh** [comment]
@bekzodrakhmatof 

Check if your region name is correct. Lookup on aws console for accurate abbreviation of region names.

**Comment by disa6302** [comment]
Ensure all the parameters are set appropriately as mentioned by @archidvignesh .
