### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by MrShiY** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#4]
_Removed for security concern_

Is there any problem with my setting?
why does app crash when signin in AWSMobileClientExtensions.swift.
self.userPoolClient is still nil, so created user is nil.

**Comment by MrShiY** [comment]
I have fixed this issue because the region is case-sensitive,
but another issue occured, error below:
Error creating channel Error Domain=com.amazonaws.AWSKinesisVideoErrorDomain Code=1 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}
Why is this?

**Comment by zhiyua-git** [comment]
Hi @MrShiY ,

Please note the user pool and identity information is sensitive and don't put those in public, you might want to delete the pool and reset.

For your latest situation, you are getting AccessDeniedException which means your role doesn't have permission for the operation, you will need to grant policy like below to your Cognito User pool role.

```
{
   "Version":"2012-10-17",
   "Statement":[
      {
	 "Effect":"Allow",
	 "Action":[
	    "kinesisvideo:DescribeSignalingChannel",
	    "kinesisvideo:CreateSignalingChannel",
	    "kinesisvideo:GetSignalingChannelEndpoint",
	    "kinesisvideo:GetIceServerConfig",
            "kinesisvideo:ConnectAsMaster",
            "kinesisvideo:ConnectAsViewer"
	 ],
	 "Resource":"arn:aws:kinesisvideo:*:*:channel/\${credentials-iot:ThingName}/*"
      }
   ]
}
```

The role of your user pool can be found the AWS IAM console, it should be default to something like **Cognito_ _PoolName_ Auth_Role**.

**Comment by MrShiY** [comment]
You are right, thanks.
