### ISSUE TITLE
Does this work for unauth users?

### ISSUE THREAD

**Issue by archidvignesh** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#41]
Was wondering, all tutorials and documentation have pointed to users being authenticated using AWS cognito in order to access kinesis. Does this work for unauth users using just identity pools?

**Comment by disa6302** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/issues/8.

Please follow this issue for any cognito related questions.
