### ISSUE TITLE
WebRTC-iOS to Amazon S3

### ISSUE THREAD

**Issue by SanthoshMKunthe** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#42]
Sorry for posting this query as issue. But I would like to know is it possible to store WebRTC-iOS streamed video in S3.
If yes could you kindly provide guidance regarding the same.

**Comment by disa6302** [comment]
We do not have in-built ingestion support with any WebRTC SDK.

**Comment by rajan0807** [comment]
Also, facing the same issue when I'm connecting with microphones audio is Fine but when I switch to speaker no audio is available.

**Comment by rajan0807** [comment]
Also, facing the same issue when I'm connecting with microphones audio is Fine but when I switch to speaker no audio is available.
