### ISSUE TITLE
WebRTC connection failing at times for prolonged duration of time.

### ISSUE THREAD

**Issue by bijuC1983** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#45]
Hello,
           We have reused classes from this project like WebRTCClient to connect to a Wifi camera using WebRTC. The app is currently in Beta and we received couple of reports of connectivity failure. Our observation so far:

- One of our Beta user is not able to connect to the camera using his iPhone 12(iOS 14.6) and iPhone XR(iOS 14.6). He has tried connecting using Vodafone Idea 4G, Jio 4G, Airtel 4G, Jio Fiber. None have worked for him. Very rarely sometimes, he is able to get access. Our support engineers, were able to access his camera using his login without any problems. One difference we noticed is that both his phones had dual SIM, one physical SIM and one e-SIM. We gave the Beta user, a release of this AWS test app and when connected as a viewer, the master feed was blank(white) for him. This was to confirm that no issue was introduced by our additional layers of code.
- One of our developers started facing the same issue after his Wifi router was changed to one that supports both 2.5Ghz and 5Ghz. The router was setup to have an AP for each respectively, 2.5Ghz & 5Ghz. The mobile device when connected to 2.5Ghz alone ( with 4G disabled) gave the following behaviour:
1. Connect Signalling client - Success
2. Send SDP Offer - Success
3. Send ICE Candidates - Success
4. Receive SDP Answer - Success
5. Peer Connection Established - Success
6. **WebRTC state changed to Failed after around on an average 18 seconds**
The behaviour was the same with this AWS Test App also. However, the WebRTC connected when the mobile device is connected to 4G(with Wifi disabled) or Wifi (with both Wifi & 4G enabled). The device used is iPhone XR and iOS 14.6. 
Surprisingly, since this morning with the same setup, the webRTC is getting connected for the developer. The situation is still the same for the Beta user with no connection.
- The behaviour is the same with disableIPv6 set to true & false. By default it is false.

We understand that there are many moving parts here and the point of failure could be any. We are looking for pointers, clues & possible resolution from your team to support us to go live.

Thanks in advance!

**Comment by bijuC1983** [comment]
Hello @disa6302 ,
                               After rigorous live testing with different users on different networks, the problem was isolated to the following:
` func checkAndAddIceCandidate(remoteCandidate: RTCIceCandidate, clientId: String) {
        **if(clientId == ""){return}**
        // if answer/offer is not received, it means peer connection is not found. Hold the received ICE candidates in the map.
        if peerConnectionFoundMap.index(forKey: clientId) == nil {
            print("SDP exchange not completed yet. Adding candidate: \(remoteCandidate.sdp) to pending queue")

            // If the entry for the client ID already exists (in case of subsequent ICE candidates), update the queue
            if pendingIceCandidatesMap.index(forKey: clientId) != nil {
                var pendingIceCandidateListByClientId: Set<RTCIceCandidate> = pendingIceCandidatesMap[clientId]!
                pendingIceCandidateListByClientId.insert(remoteCandidate)
                pendingIceCandidatesMap[clientId] = pendingIceCandidateListByClientId
            }
            // If the first ICE candidate before peer connection is received, add entry to map and ICE candidate to a queue
            else {
                var pendingIceCandidateListByClientId = Set<RTCIceCandidate>()
                pendingIceCandidateListByClientId.insert(remoteCandidate)
                pendingIceCandidatesMap[clientId] = pendingIceCandidateListByClientId
            }
        }
        // This is the case where peer connection is established and ICE candidates are received for the established connection
        else {
            print("Peer connection found already")
            // Remote sent us ICE candidates, add to local peer connection
            let peerConnectionCurrent : RTCPeerConnection = peerConnectionFoundMap[clientId]!
            peerConnectionCurrent.add(remoteCandidate);
            print("Added ice candidate \(remoteCandidate.sdp)");
        }
    }`
This method was added in the last merge in order to handle out of turn ICE candidates as per the PR request. It uses a dictionary with the client Id as key to maintain the pending Ice Candidates by Client Id. We had noticed that sometimes, the app crashed with a EXC_BAD_ACCESS crash at:
`pendingIceCandidateListByClientId.insert(remoteCandidate)`
Our engineers, added some debug and prematurely concluded that this maybe when client id is received as empty(""). As error handling, the following statement was added which was causing the WebRTC to fail on many but certain network combinations. On certain networks like Airtel 4G, it worked 100% of the time.
`if(clientId == ""){return}`
Removing this statement, made it to work again on all networks with consistency. Hence, could you help us with the following:

- pendingIceCandidatesMap is a dictionary with clientId as the key. It seems a bit odd that the clientId is received empty almost all the time. Is it expected and natural?
- We suspect the Exec_Bad_Access could be happening sometimes due to some race condition considering the nature of these messages. Could you think of any reasons why this may be happening and suggest possible resolution.

Thank you in advance!

**Comment by unicornss** [comment]
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis-1.htmlhttps://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-websocket-apis-2.html

**Comment by unicornss** [comment]
@bijuC1983 ,
Given 

>  Removing this statement, made it to work again on all networks with  consistency.

closing the issue for now. Please re-open or create a new one as needed.
