### ISSUE TITLE
Speaker Issue

### ISSUE THREAD

**Issue by Emefar** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#46]
Hello. I cannot use in speaker mode. I added do-catch block for catch error. I used demo app.
```
do {
    try AVAudioSession.sharedInstance().overrideOutputAudioPort(.speaker)
}catch {
    print("error ", error.localizedDescription)
}
```
**The operation couldn’t be completed. (OSStatus error -50.)**

**Comment by disa6302** [comment]
@Emefar , 

This is not a KVS specific issue. Please direct the question to ios forums.

**Comment by ankitsaini56** [comment]
@Emefar did you find any solution for this?

**Comment by Emefar** [comment]
@ankitsaini56 Unfortunately no
