### ISSUE TITLE
WSError(type: Starscream.ErrorType.upgradeError, message: \"Invalid HTTP upgrade\", code: 400)

### ISSUE THREAD

**Issue by haihm1997** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#51]
Hi everyone!
I'm writing an app using AWS WebRTC SDK for iOS and facing an issue about signing:
"Disconnected from signaling. WSError(type: Starscream.ErrorType.upgradeError, message: \"Invalid HTTP upgrade\", code: 400)"
My project has credential, channel ARN and HTTP(WSS) endpoint are got from Backend.
I'm using Starscream (3.1.1)
This is my WSS URL that I used to init SignalingClient

![image](https://user-images.githubusercontent.com/50571326/148491966-1032eea5-7041-4bc5-b161-6990986bcda3.png)
Please help me a solution!

**Comment by tylerjames** [comment]
I'm getting the same issue using Starscream 4.0.4
and also seeing it conjunction with:

> Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002)

I was able to run the demo but after incorporating the functionality into my code I'm encountering this when trying to connect the signalling client. 

Also my app is using Swift 5

**Comment by haihm1997** [comment]
Resolved!
This issue occur due I passing incorrect channel_arn format value

**Comment by pablogeek** [comment]
@haihm1997 can you clarify?

**Comment by jhoughjr** [comment]
literally never seen a ws lib connect method say a ws connection was not an upgrade when other ws clients connected to the same server fine. what good is the autobahn test suite passing, supposedly if masked data isn't supported?
