### ISSUE TITLE
[Question] Is there an example / sample code on how to use webrtc viewer in flutter

### ISSUE THREAD

**Issue by gkamath** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#52]
I am developing an app using flutter where I am trying to implement a webrtc viewer that will start a peer to peer Streaming between [Embedded SDK] master and iOS device. I was not able to find a flutter implementation.

Can you suggest if there is any doc on how to use this sdk in flutter (via channel) or point me to kinesis-webrtc-sdk-flutter.

**Comment by disa6302** [comment]
We do not have any sample integration in flutter.
