### ISSUE TITLE
Error when I run a project

### ISSUE THREAD

**Issue by Moriarty1230** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#53]
no such module 'awscognitoidentityprovider'
Hi, I want to try the Kinesis Video Stream sample for ios. when I try to build the app, I got this error. I have been removed Pods dir and rerun pod install multiple times or recreate project still get the same error. I really appreciate any help. Thank you
![caf65e94fdfd286597617b2b8846021](https://user-images.githubusercontent.com/47554274/159636594-f64728d5-03d7-4660-97a3-8123aa0aebcd.jpg)
This is my pod file list
![582862da195147b011500b08fa73198](https://user-images.githubusercontent.com/47554274/159636501-ec794167-665c-45e1-9fd7-8ab97c0b0f77.jpg)

**Comment by maxwell44** [comment]
![image](https://user-images.githubusercontent.com/7741164/159836776-04a9bf22-9980-48f9-920f-9ac84ecebe73.png)

Comment out the code above and use SPM to install

**Comment by disa6302** [comment]
@Moriarty1230 ,

Do you see any errors while running pods install?

**Comment by Moriarty1230** [comment]
![image](https://user-images.githubusercontent.com/47554274/160334214-d465f857-a818-430a-8dab-3095aafda7a9.png)
There is no error. @disa6302

**Comment by disa6302** [comment]
I see this problem on XCode version 13, however, it seems to work on XCode 11. Can you verify if you are facing the same issue on XCode 11?

**Comment by maxwell44** [comment]
use spm

**Comment by mehmetcy84** [comment]
> use spm

I also face the same issue, and could run the sample app only by installing XCode 11.

What is spm, and how it is used to remedy this issue, could you explain please?

**Comment by maxwell44** [comment]
> swift package

**Comment by mgmtcam22** [comment]
> > swift package
I tried SPM and got a mistake No such module 'AWSCognitoIdentityProvider' near  import AWSCognitoIdentityProvider 
Do you know how to fix it ?

**Comment by benwkim** [comment]
I was able to resolve the build issues with the following steps:
1. In project Build Settings, delete the VALID_ARCHS field (In both `PROJECT` and `TARGETS -> AWSKinesisVideoWebRTCDemoApp`)
2. Add a case for `.webrtc` in this [switch statement](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/master/Swift/KVSiOSApp/ChannelConfigurationViewController.swift#L263) (it can be a no-op)
