### ISSUE TITLE
Error when I run a project Click Sign In Button

### ISSUE THREAD

**Issue by maxwell44** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#54]
I click the login button crash

crash Info： Thread 1: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value

The commented code is the very beginning code of this project.

Code without comments I refer to the code under this link.

https://docs.amplify.aws/sdk/auth/working-with-api/q/platform/ios/#re-send-a-confirmation-code-mfa

![671648101784_ pic](https://user-images.githubusercontent.com/7741164/159858429-3c1eedd6-0a4f-4e04-a822-369508abc9d4.jpg)

**Comment by disa6302** [comment]
I am unable to reproduce this issue with top of master. Any code changes you have made?

**Comment by maxwell44** [comment]
no code changes

**Comment by maxwell44** [comment]
> I am unable to reproduce this issue with top of master. Any code changes you have made?

no code changes

**Comment by disa6302** [comment]
@maxwell44 , 
Looks like there is a problem with newer Xcode versions. Can you try this with XCode 11 instead?

**Comment by maxwell44** [comment]
> @maxwell44 , Looks like there is a problem with newer Xcode versions. Can you try this with XCode 11 instead?

use Xcode14 or Xcode13

**Comment by OwlRepo** [comment]
Also experiencing this issue after I have updated my MacOS(Ventura 13.4(22F66)) and XCode(Version 14.3.1 (14E300c)) to latest version.

**Comment by sirknightj** [comment]
See #69.
