### ISSUE TITLE
AWSMobileClient Sign In Error

### ISSUE THREAD

**Issue by OwlRepo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#69]
After updating to the latest MacOS and XCode version, any work around for this? 

I have also tried to hard code the username and password to make sure there's a value but the error below still persists.

<img width="1470" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/62129334/ec309737-2922-4c30-af15-9a4c07ef27a1">

**Comment by sirknightj** [comment]
Hi @OwlRepo, was it working previously before updating, but after the update, it no longer works?

I am using MacOS 13.4 (22F66) and XCode 14.3 (14E222b) and can confirm it is working as of this version. Can you confirm that both your awsconfiguration.json and Constants.swift have their values in the correct places and none of the properties were accidentally swapped (example in the readme)?

<img width="441" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/14988194/f072f3a8-9a82-4d95-bebf-ccf12bd2edc5">


Additionally, could you also confirm that the awsconfiguration.json is correctly formatted. That is, there are no missing `"`, `:`, or `{`. You can also use a json validator tool to confirm that the json object is formatted correctly.

When I removed one of the `}` from my awsconfiguration.json, I encountered the same error:

```
AWSMobileClient/AWSMobileClient+SignIn.swift:65: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2023-06-19 16:25:29.798626-0700 AWSKinesisVideoWebRTCDemoApp[51205:6393314] AWSMobileClient/AWSMobileClient+SignIn.swift:65: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by OwlRepo** [comment]
@sirknightj May I know where i can find or where do I need to create the awsconfiguration.json file? Thank you very much for responding!
