### ISSUE TITLE
failed with error 0 : [0x00000041] No route to host

### ISSUE THREAD

**Issue by OwlRepo** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#70]
After rebasing my branch from master branch (git pull --rebase origin master). It has no merge conflicts but this error keeps popping up and causes the stream to not load.

I have used the webrtc_ios manual build framework but I did not apply changes to it yet. I just compiled it using ninja because I want to see first if the manual build WebRTC.xcframework is working.

<img width="1630" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/62129334/b256af08-5eb0-44b9-b80a-89656e744683">

So to confirm if there is a bug in my manual build, I tried to revert it back to using GoogleWebRtc Cocoapod but it still giving me this error.

<img width="1652" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/62129334/d0d7889a-1e5e-419c-a0b1-99ccef0696e0">

**Comment by sirknightj** [comment]
It looks like your iOS client wasn't able to successfully establish a connection to the peer (as indicated by no route to host).

Are you able to get the sample application to connect to https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html?

You may also want to check out the troubleshooting guide https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/troubleshooting.html or also reach out on the WebRTC forums https://groups.google.com/g/discuss-webrtc
