### ISSUE TITLE
There is memory leak. where can I fix it?

### ISSUE THREAD

**Issue by Bhoon-coding** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#71]
when connecting others for a long time. 
My app is overload because of memory leak. 
where can I find memory leak things? 
I thought peerconnection is the reason in `WebRTCClient.swift` 

![Snipaste_2023-07-11_14-07-41](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/64088377/2194d1b2-cf9e-40c4-a02e-c4665422d646)

**Comment by sirknightj** [comment]
> when connecting others for a long time.

Could you share more details on how long the connections have been running in your test client applications?

> My app is overload because of memory leak.

Also, please share details on:
a) how are you testing the memory consumption
b) the actual details on memory usage / findings from the memory utilization tool and the logs?

Has there been any changes to the client sample application - e.g. closing and reopening client connections in your test setup? Are you using a real device or using the iOS simulator (XCode)? What steps do we need to take to replicate this using the stock sample (without any modifications)?
