### ISSUE TITLE
ResourceNotFoundException 

### ISSUE THREAD

**Issue by JinTae89** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#80]
I developed a video call app using this SDK.

The service has been running without any problems for two years, and we recently discovered a user who was having a problem.

This problem is occurring to a very small number of users.

<img width="885" alt="image" src="https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/104581537/02160e8c-31e2-4aae-82e8-97ba64ef3ffb">

How can I solve this problem?

**Comment by sirknightj** [comment]
A resource not found exception occurs when Amazon Kinesis Video Streams can't find the signaling channel that was specified in the request (for example, [`DescribeSignalingChannel`](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_DescribeSignalingChannel.html)). Please make sure that the signaling channel exists within the AWS account in the correct region. (Create one if it doesn't exist via [`CreateSignalingChannel`](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_CreateSignalingChannel.html).)

**Comment by Bhoon-coding** [comment]
I got same issue. only call createSignalingChannel method.
I tried to create signaling channel by channelName and checked channelName doesn't nil.
Here is my code 
```swift 
private func createChannel(channelName: String, completion: ((String?) -> Void)? = nil) {
        let kvsClient = AWSKinesisVideo(forKey: awsKinesisVideoKey)
        guard let createSignalingChannelInput = AWSKinesisVideoCreateSignalingChannelInput() else {
            print("createSigalingChannelInput 생성실패")
            return
        }
        createSignalingChannelInput.channelName = channelName
        print("createSignalingChannelInput: \(createSignalingChannelInput)")
        // MARK: - Here's problem thing
        kvsClient.createSignalingChannel(createSignalingChannelInput) { [weak self] result, error in
            guard let strongSelf = self else { return }
                if let error = error {
                    print("\(#function) error: \(error.localizedDescription)")
                    
                } else {
                    strongSelf.channelARN = result?.channelARN
                    completion?(strongSelf.channelARN)
                    print("Channel ARN : ", result?.channelARN ?? "No Channel")
                }
                return
        }
        // MARK: - channelARN이 없을 수 있나. (channelARN 생성에 실패했다면 error로 빠졌을것)
        if channelARN == nil {
            ErrorReportManager.shared.log(
                message: "\(self)_\(#function): channelARN == nil"
            )
            print("Unable to create channel Please validate all the input fields ")
            return
        }
}
```
