### ISSUE TITLE
Microphone permission is getting asked from sdk after successful peer connection. How to stop that?

### ISSUE THREAD

**Issue by ankitsaini56** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#83]
As soon as webrtc connection is done, getting mircophone permission popup, how to disable that ?

**Comment by ceaglest** [comment]
@ankitsaini56 are you publishing an audio track on the iOS side? You could disable audio when calling: [WebRTCClient.init](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/95f10b63dc09693bc27b792529f79a1a2423f8d6/Swift/KVSiOSApp/WebRTCClient.swift#L35):

```
    required init(iceServers: [RTCIceServer], isAudioOn: Bool) {
```

Publishing audio uses the microphone and requires permissions.

**Comment by niyatim23** [comment]
Closing assuming answered. Feel free to reopen if the issue persists
