### ISSUE TITLE
What are the changes we need to do in webrtc iOS example for allow guest users?

### ISSUE THREAD

**Issue by vivekgadgeon** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#85]
I was testing the iOS example for webrtc. For authenticated users, it works fine. But for guest users, it shows access denied. 

I have done the changes that was said in the issue id: #8, but I got the following issue:

Error creating channel Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=6 "(null)" UserInfo={__type=InvalidParameterException, message=Basic (classic) flow is not enabled, please use enhanced flow.}

What are the steps I need to do in the example project to make work it work for guest users?

**Comment by niyatim23** [comment]
This is not related to WebRTC iOS but with Cognito. Unfortunately we cannot help you with Cognito related issues. Please ask this question in an appropriate forum
