### ISSUE TITLE
How to get audio track？

### ISSUE THREAD

**Issue by meroger** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#86]
I can easily get video frames to do screenshots, but I can't get audio frames to make video to save locally.
How do I get the audio track?

**Comment by disa6302** [comment]
@meroger , 

Can you include more details on what the issue is? We already support adding audio track here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/master/Swift/KVSiOSApp/WebRTCClient.swift#L233-L238

**Comment by meroger** [comment]
![WX20240305-084107](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/assets/16462535/4ac0ccd7-9c29-435b-998f-e81e0220fc70)
Here's how I get the video frame, inheriting RTCMTLVideoView and getting the video frame from the parent method.  But how do I get audio frames?

**Comment by niyatim23** [comment]
Unfortunately the API for that is not exposed by libwebrtc [here](https://chromium.googlesource.com/external/webrtc/+/9eeb6240c93efe2219d4d6f4cf706030e00f64d7/webrtc/sdk/objc/Framework/Headers/WebRTC)
