### ISSUE TITLE
use webrtc-sdk-ios  the ipa will increased about 25M 

### ISSUE THREAD

**Issue by jemery001** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#9]
hi 
 When i add  the sdk to mine project， i found that the ipa increased about 25M ？
 I found it contains these（AWSCognitoIdentityProvider AWSMobileClient AWSKinesisVideo AWSKinesisVideoSignaling GoogleWebRTC）
Are these necessary？

When i add  the  Android  sdk to mine project ，the apk just  increased about 2M ，so  the size of iOS can be Compressed？ thx

**Comment by sharadrj** [comment]
It would be good to figure out how much of the size increase is coming from kinesis video components and what is coming from GoogleWebRTC, AWSMobileClient and AWSCognitoIdentityProvider.

**Comment by jemery001** [comment]
hi 
AWSKinesisVideo.framework and AWSKinesisVideoSignaling.framework size is 1.2M. And the WebRTC.framework size is 6M.   these are AWSCognitoIdentityProvider.framework，AWSCognitoIdentityProviderASF.framework，AWSCore.framework， AWSMobileClient.framework，Starscream.framework  size are 17.3M. Are these necessary？

**Comment by sharadrj** [comment]
Unfortunately, the only components we control here are AWSKinesisVideo.framework and AWSKinesisVideoSignaling.framework. 

Other AWS components are from AWS SDK for iOS which are managed by AWS Mobile SDK group. 
https://docs.aws.amazon.com/sdk-for-ios/index.html

**Comment by MushMal** [comment]
Resolving. This issue is not specific to the AWS KVS
