### ISSUE TITLE
cognitoIdentityUserPoolAppClientSecret unsafe

### ISSUE THREAD

**Issue by zhangshouyin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#90]
There is a cognitoIdentityUserPoolAppClientSecret key in the amazon-kinesis-video-streams-webrtc-sdk-ios that is hard-coded in the configuration file, which is not safe. Is there a way to replace this practice?

**Comment by niyatim23** [comment]
That is an example. It is not an actual secret value
