### ISSUE TITLE
Is it possible to receive video from multiple WebRTC connections with multiple signaling clients simultaneously?

### ISSUE THREAD

**Issue by mehmetcy84** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#92]
I am developing an app which makes use of the sample code from the latest master. I'd like my app to:

- Connect to multiple cameras simultaneously to receive video stream from multiple cameras. (multiple peer connections)
- Make separate signaling connections for each peer connection. (multiple signaling clients)
(My app doesn't need to capture video and stream out anything.)

What I'd like to understand is:

- Whether this is possible with the current state of the codebase without modifying the WebRTCClient.swift and the SignalingClient.swift files? (Apart from the changes required on the app level to use these classes) 
- Is this possible, using the latest master branch, or do I have to use the multiple-viewer-sample branch?

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/compare/master...multiple-viewer-sample

Thanks,

**Comment by stefankiesz** [comment]
Hi @mehmetcy84, using the sample app and application in such a way has not been tested, so I cannot guarantee that this will work, but we'll leave this issue open so that we may consider this as a feature request to our current demo application.

**Comment by mehmetcy84** [comment]
> Hi @mehmetcy84, using the sample app and application in such a way has not been tested, so I cannot guarantee that this will work, but we'll leave this issue open so that we may consider this as a feature request to our current demo application.

My initial testing shows that using multiple instances of WebRTCClient and SignalingClient classes, multiple simultaneous WebRTC streams can be received using the Master branch. As far as I understood, multiple-viewer-branch is not related with this feature, but is related to serving as a master to multiple viewers on different endpoints using the same signaling channel.

**Comment by stefankiesz** [comment]
Great to hear it's working! Going to close this now, but feel free to open a new issue if you have any more questions or issues.
