### ISSUE TITLE
Can't build and run, Swift Compiler Error, Definition conflicts with previous value, Value of optional type 'String?' must be unwrapped to a value of type 'String'

### ISSUE THREAD

**Issue by thachnv92** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#93]
Hi,

I updated awsconfiguration.json and Constants.swift. But can't build project.
I use Mac Pro with Catalina 10.15.7 and Xcode 12.4.
This is issue:

- Swift Compiler Error
- Definition conflicts with previous value
- Value of optional type 'String?' must be unwrapped to a value of type 'String'

![Screen Shot 2024-10-28 at 20 00 29](https://github.com/user-attachments/assets/5fcd7705-ad96-4afa-83e0-b33cca156abe)

Please help me.
Thank you.

**Comment by sirknightj** [comment]
Hi,

You can revert the project back to the original state, with just the "Unknown" region replaced to a valid region, and try building from there.

You can run `git diff` from the project root directory to check which constants were modified. Please check that all of the constants edited in Constants.swift that were edited have matching quotes.

I pulled the latest using Mac 14.7 (23H124) and XCode Version 15.3 (15E204a), and am able to connect to https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js and https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c.
